#include "Catstructor.h"

/*
* Appearance persistence, clipboard data copy support, PNG capture...
*/

static const char* FormatAppearanceIDToken(AppearanceField field, int value, char* buffer, size_t bufferSize)
{
    if (field >= 0 && field < APPEARANCE_FIELD_COUNT && g_namedAppearanceIDs[field][0])
    {
        return g_namedAppearanceIDs[field];
    }

    snprintf(buffer, bufferSize, "%d", value);
    return buffer;
}

static int FormatAppearanceText(const uint8_t* parts, char* text, size_t textSize)
{
    AppearanceSnapshot value;
    SYSTEMTIME now;

    char palette[32];
    char body[32];
    char head[32];
    char tail[32];
    char leg1[32];
    char leg2[32];
    char arm1[32];
    char arm2[32];
    char lefteye[32];
    char righteye[32];
    char lefteyebrow[32];
    char righteyebrow[32];
    char leftear[32];
    char rightear[32];
    char mouth[32];
    int textLength;

    ReadAppearance(parts, &value);
    GetLocalTime(&now);

    // This is super cursed, but I don't give a fuck...
    textLength = snprintf(
        text,
        textSize,
        "// Generated by " MOD_NAME "!\r\n"
        "// Paste this block into your custom_cats.gon.append and name it appropriately!\r\n"
        "Cat_%04u%02u%02u_%02u%02u%02u {\r\n"
        "    default_frame %d\r\n"
        "    texture %d\r\n"
        "    claws %d\r\n"
        "    palette %s\r\n"
        "    body %s\r\n"
        "    head %s\r\n"
        "    tail %s\r\n"
        "    leg1 %s\r\n"
        "    leg2 %s\r\n"
        "    arm1 %s\r\n"
        "    arm2 %s\r\n"
        "    lefteye %s\r\n"
        "    righteye %s\r\n"
        "    lefteyebrow %s\r\n"
        "    righteyebrow %s\r\n"
        "    leftear %s\r\n"
        "    rightear %s\r\n"
        "    mouth %s\r\n"
        "    voice %s\r\n"
        "    pitch %.3f\r\n"
        "}\r\n",
        (unsigned int)now.wYear,
        (unsigned int)now.wMonth,
        (unsigned int)now.wDay,
        (unsigned int)now.wHour,
        (unsigned int)now.wMinute,
        (unsigned int)now.wSecond,
        APPEARANCE_DEFAULT_FRAME,
        value.texture,
        value.claws,
        FormatAppearanceIDToken(
            APPEARANCE_FIELD_PALETTE,
            value.palette,
            palette,
            sizeof(palette)
        ),
        FormatAppearanceIDToken(
            APPEARANCE_FIELD_BODY,
            value.body,
            body,
            sizeof(body)
        ),
        FormatAppearanceIDToken(
            APPEARANCE_FIELD_HEAD,
            value.head,
            head,
            sizeof(head)
        ),
        FormatAppearanceIDToken(
            APPEARANCE_FIELD_TAIL,
            value.tail,
            tail,
            sizeof(tail)
        ),
        FormatAppearanceIDToken(
            APPEARANCE_FIELD_LEG1,
            value.leg1,
            leg1,
            sizeof(leg1)
        ),
        FormatAppearanceIDToken(
            APPEARANCE_FIELD_LEG2,
            value.leg2,
            leg2,
            sizeof(leg2)
        ),
        FormatAppearanceIDToken(
            APPEARANCE_FIELD_ARM1,
            value.arm1,
            arm1,
            sizeof(arm1)
        ),
        FormatAppearanceIDToken(
            APPEARANCE_FIELD_ARM2,
            value.arm2,
            arm2,
            sizeof(arm2)
        ),
        FormatAppearanceIDToken(
            APPEARANCE_FIELD_LEFTEYE,
            value.lefteye,
            lefteye,
            sizeof(lefteye)
        ),
        FormatAppearanceIDToken(
            APPEARANCE_FIELD_RIGHTEYE,
            value.righteye,
            righteye,
            sizeof(righteye)
        ),
        FormatAppearanceIDToken(
            APPEARANCE_FIELD_LEFTEYEBROW,
            value.lefteyebrow,
            lefteyebrow,
            sizeof(lefteyebrow)
        ),
        FormatAppearanceIDToken(
            APPEARANCE_FIELD_RIGHTEYEBROW,
            value.righteyebrow,
            righteyebrow,
            sizeof(righteyebrow)
        ),
        FormatAppearanceIDToken(
            APPEARANCE_FIELD_LEFTEAR,
            value.leftear,
            leftear,
            sizeof(leftear)
        ),
        FormatAppearanceIDToken(
            APPEARANCE_FIELD_RIGHTEAR,
            value.rightear,
            rightear,
            sizeof(rightear)
        ),
        FormatAppearanceIDToken(
            APPEARANCE_FIELD_MOUTH,
            value.mouth,
            mouth,
            sizeof(mouth)
        ),
        value.voice,
        ClampVoicePitch(value.voicePitch)
    );

    if (textLength <= 0 || (size_t)textLength >= textSize)
    {
        return 0;
    }

    return textLength;
}

static const char* AppearanceFileName(const char* path)
{
    const char* slash;

    slash = strrchr(path, '\\');
    return slash ? slash + 1 : path;
}

static int BuildAppearanceDirectory(char* directory, size_t directorySize)
{
    char modulePath[MAX_PATH];
    char* slash;
    int length;

    if (!directory || directorySize == 0 || !g_module || !GetModuleFileNameA(g_module, modulePath, MAX_PATH))
    {
        return 0;
    }

    slash = strrchr(modulePath, '\\');

    if (!slash)
    {
        return 0;
    }

    *slash = '\0';
    length = snprintf(directory, directorySize, "%s\\saved_cats", modulePath);
    return length > 0 && (size_t)length < directorySize;
}

static int EnsureAppearanceDirectory(char* directory, size_t directorySize)
{
    DWORD error;

    if (!BuildAppearanceDirectory(directory, directorySize))
    {
        AddDebugMessage("Save unavailable: Mod DLL directory was not found!");
        return 0;
    }

    if (CreateDirectoryA(directory, NULL))
    {
        return 1;
    }

    error = GetLastError();

    if (error == ERROR_ALREADY_EXISTS)
    {
        return 1;
    }

    AddDebugMessage("Save unavailable: saved cats directory could not be created!");
    Log("Could not create appearance directory %s (error %lu)!", directory, error);
    return 0;
}

static const char* FindSubstring(const char* text, const char* needle)
{
    size_t needleLength;

    needleLength = strlen(needle);

    if (needleLength == 0)
    {
        return text;
    }

    while (*text)
    {
        if (*text == *needle && memcmp(text, needle, needleLength) == 0)
        {
            return text;
        }

        ++text;
    }

    return NULL;
}

static int IsAppearanceNameCharacter(char value)
{
    return (value >= 'a' && value <= 'z') || (value >= 'A' && value <= 'Z') || (value >= '0' && value <= '9') || value == '_';
}

static const char* FindNamedAppearanceData(const char* text, const char* name)
{
    const char* match;
    const char* cursor;
    size_t nameLength;

    if (!text || !name || !name[0])
    {
        return NULL;
    }

    nameLength = strlen(name);
    match = text;

    while ((match = FindSubstring(match, name)) != NULL)
    {
        if ((match == text || !IsAppearanceNameCharacter(match[-1])) && !IsAppearanceNameCharacter(match[nameLength]))
        {
            cursor = match + nameLength;

            while (*cursor == ' ' || *cursor == '\t' || *cursor == '=')
            {
                ++cursor;
            }

            return cursor;
        }

        match += nameLength;
    }

    return NULL;
}

static int ReadNamedAppearanceValue(const char* text, const char* name, int* outValue)
{
    const char* cursor;
    unsigned int value;

    cursor = FindNamedAppearanceData(text, name);

    if (!cursor || *cursor < '0' || *cursor > '9')
    {
        return 0;
    }

    value = 0;

    while (*cursor >= '0' && *cursor <= '9')
    {
        value = value * 10U + (unsigned int)(*cursor - '0');

        if (value > APPEARANCE_MAX_ID)
        {
            value = APPEARANCE_MAX_ID;
            break;
        }

        ++cursor;
    }

    *outValue = (int)value;
    return 1;
}

static int ReadNamedAppearanceString(const char* text, const char* name, char* outValue, size_t outSize)
{
    const char* cursor;
    char terminator;
    size_t length;

    if (!outValue || outSize == 0)
    {
        return 0;
    }

    cursor = FindNamedAppearanceData(text, name);

    if (!cursor || !cursor[0])
    {
        return 0;
    }

    terminator = '\0';

    if (*cursor == '"' || *cursor == '\'')
    {
        terminator = *cursor;
        ++cursor;
    }

    length = 0;

    while (*cursor && ((terminator && *cursor != terminator) || (!terminator && *cursor != ' ' && *cursor != '\t' && *cursor != '\r' && *cursor != '\n' && *cursor != '}')))
    {
        if (length + 1 >= outSize)
        {
            return 0;
        }

        outValue[length++] = *cursor++;
    }

    if (length == 0 || (terminator && *cursor != terminator))
    {
        return 0;
    }

    outValue[length] = '\0';
    return 1;
}

static int ReadNamedAppearanceIDValue(const char* text, const char* name, AppearanceField field, int* outValue)
{
    char token[NAMED_ID_BUFFER_SIZE];
    int value;

    if (!outValue)
    {
        return 0;
    }

    if (ReadNamedAppearanceValue(text, name, &value))
    {
        *outValue = value;
        SetNamedAppearanceID(field, NULL);
        return 1;
    }

    if (!ReadNamedAppearanceString(text, name, token, sizeof(token)) || token[0] != '@' || !ResolveNamedAppearanceID(field, token, &value))
    {
        return 0;
    }

    *outValue = value;
    SetNamedAppearanceID(field, token);
    return 1;
}

static int ReadNamedAppearanceDouble(const char* text, const char* name, double* outValue)
{
    const char* cursor;
    double value;
    double place;
    int foundDigit;

    if (!outValue)
    {
        return 0;
    }

    cursor = FindNamedAppearanceData(text, name);

    if (!cursor)
    {
        return 0;
    }

    value = 0.0;
    foundDigit = 0;

    while (*cursor >= '0' && *cursor <= '9')
    {
        value = value * 10.0 + (double)(*cursor - '0');
        foundDigit = 1;
        ++cursor;
    }

    if (*cursor == '.')
    {
        ++cursor;
        place = 0.1;

        while (*cursor >= '0' && *cursor <= '9')
        {
            value += (double)(*cursor - '0') * place;
            place *= 0.1;
            foundDigit = 1;
            ++cursor;
        }
    }

    if (!foundDigit)
    {
        return 0;
    }

    *outValue = value;
    return 1;
}

static int LoadAppearanceFile(uint8_t* parts, int* defaultFrame, const char* path)
{
    AppearanceSnapshot appearance;
    char text[APPEARANCE_TEXT_BUFFER_SIZE];
    HANDLE file;
    DWORD fileSize;
    DWORD highSize;
    DWORD readSize;
    int fieldValue;
    double pitchValue;
    int loadedFields;

    file = CreateFileA(path, GENERIC_READ, FILE_SHARE_READ, NULL, OPEN_EXISTING, FILE_ATTRIBUTE_NORMAL, NULL);

    if (file == INVALID_HANDLE_VALUE)
    {
        AddDebugMessage("Load failed: Could not open the selected file!");
        return 0;
    }

    highSize = 0;
    fileSize = GetFileSize(file, &highSize);

    if (fileSize == 0 || fileSize == INVALID_FILE_SIZE || highSize != 0 || fileSize >= (DWORD)sizeof(text))
    {
        CloseHandle(file);
        AddDebugMessage("Load failed: Invalid or oversized .catstruct file!");
        return 0;
    }

    readSize = 0;

    if (!ReadFile(file, text, fileSize, &readSize, NULL) || readSize != fileSize)
    {
        CloseHandle(file);
        AddDebugMessage("Load failed: The .catstruct file could not be read!");
        return 0;
    }

    CloseHandle(file);
    text[readSize] = '\0';

    if (!defaultFrame)
    {
        AddDebugMessage("Load failed: Default-frame state unavailable!");
        return 0;
    }

    *defaultFrame = APPEARANCE_DEFAULT_FRAME;

    ReadAppearance(parts, &appearance);
    loadedFields = 0;

    if (ReadNamedAppearanceValue(text, "claws", &fieldValue))
    {
        appearance.claws = ClampAppearanceID(fieldValue, CLAWS_ENABLED_VALUE);
        ++loadedFields;
    }

#define LOAD_APPEARANCE_FIELD(name, member, field) \
    do \
    { \
        if (ReadNamedAppearanceIDValue(text, name, field, &fieldValue)) \
        { \
            appearance.member = fieldValue; \
            ++loadedFields; \
        } \
    } while (0)

    LOAD_APPEARANCE_FIELD("texture", texture, APPEARANCE_FIELD_TEXTURE);
    LOAD_APPEARANCE_FIELD("palette", palette, APPEARANCE_FIELD_PALETTE);
    LOAD_APPEARANCE_FIELD("body", body, APPEARANCE_FIELD_BODY);
    LOAD_APPEARANCE_FIELD("head", head, APPEARANCE_FIELD_HEAD);
    LOAD_APPEARANCE_FIELD("tail", tail, APPEARANCE_FIELD_TAIL);
    LOAD_APPEARANCE_FIELD("leg1", leg1, APPEARANCE_FIELD_LEG1);
    LOAD_APPEARANCE_FIELD("leg2", leg2, APPEARANCE_FIELD_LEG2);
    LOAD_APPEARANCE_FIELD("arm1", arm1, APPEARANCE_FIELD_ARM1);
    LOAD_APPEARANCE_FIELD("arm2", arm2, APPEARANCE_FIELD_ARM2);
    LOAD_APPEARANCE_FIELD("lefteye", lefteye, APPEARANCE_FIELD_LEFTEYE);
    LOAD_APPEARANCE_FIELD("righteye", righteye, APPEARANCE_FIELD_RIGHTEYE);
    LOAD_APPEARANCE_FIELD("lefteyebrow", lefteyebrow, APPEARANCE_FIELD_LEFTEYEBROW);
    LOAD_APPEARANCE_FIELD("righteyebrow", righteyebrow, APPEARANCE_FIELD_RIGHTEYEBROW);
    LOAD_APPEARANCE_FIELD("leftear", leftear, APPEARANCE_FIELD_LEFTEAR);
    LOAD_APPEARANCE_FIELD("rightear", rightear, APPEARANCE_FIELD_RIGHTEAR);
    LOAD_APPEARANCE_FIELD("mouth", mouth, APPEARANCE_FIELD_MOUTH);
#undef LOAD_APPEARANCE_FIELD

    if (ReadNamedAppearanceString(text, "voice", appearance.voice, sizeof(appearance.voice)))
    {
        ++loadedFields;
    }

    if (ReadNamedAppearanceDouble(text, "pitch", &pitchValue))
    {
        appearance.voicePitch = ClampVoicePitch(pitchValue);
        ++loadedFields;
    }

    if (loadedFields == 0)
    {
        AddDebugMessage("Load failed: No fields were found!");
        return 0;
    }

    ApplyAppearance(parts, &appearance);
    memset(g_idInputStates, 0, sizeof(g_idInputStates));
    g_activeIDInput = APPEARANCE_FIELD_COUNT;
    g_selectedPresetName[0] = '\0';
    snprintf(g_activeAppearancePath, sizeof(g_activeAppearancePath), "%s", path);
    AddDebugMessage("Loaded %d fields from %s!", loadedFields, AppearanceFileName(path));
    Log("Loaded %d fields from %s!", loadedFields, path);
    return 1;
}

static int DeleteAppearanceFile(const char* path)
{
    if (!DeleteFileA(path))
    {
        AddDebugMessage("Delete failed: %s", AppearanceFileName(path));
        Log("Could not delete file %s (error %lu)!", path, GetLastError());
        return 0;
    }

    if (strcmp(g_activeAppearancePath, path) == 0)
    {
        g_activeAppearancePath[0] = '\0';
    }

    AddDebugMessage("Deleted cat: %s", AppearanceFileName(path));
    Log("Deleted cat file %s!", path);
    return 1;
}

int DrawSavedAppearanceFiles(uint8_t* parts, int* defaultFrame)
{
    WIN32_FIND_DATAA data;
    char directory[MAX_PATH + 32];
    char pattern[560];
    char path[800];
    char fileLabel[MAX_PATH + 64];
    char deleteLabel[96];
    float automaticSize[2];
    float fileNameSize[2];
    float deleteButtonSize[2];
    const char* preview;
    HANDLE search;
    int changed;
    int fileCount;
    int pathLength;
    int isActive;

    if (!parts || !defaultFrame || !g_imguiBeginCombo)
    {
        return 0;
    }

    automaticSize[0] = 0.0f;
    automaticSize[1] = 0.0f;
    fileNameSize[0] = DEBUG_FILE_NAME_WIDTH;
    fileNameSize[1] = 0.0f;
    deleteButtonSize[0] = DEBUG_DELETE_BUTTON_WIDTH;
    deleteButtonSize[1] = 0.0f;

    if (!EnsureAppearanceDirectory(directory, sizeof(directory)))
    {
        return 0;
    }

    preview = g_activeAppearancePath[0] ? AppearanceFileName(g_activeAppearancePath) : "select saved cat";
    SetNextItemWidth(DEBUG_PRESET_COMBO_WIDTH);

    if (!g_imguiBeginCombo("saved cats##saved_appearance_combo", preview, 0))
    {
        return 0;
    }

    snprintf(pattern, sizeof(pattern), "%s\\*.catstruct", directory);
    search = FindFirstFileA(pattern, &data);

    if (search == INVALID_HANDLE_VALUE)
    {
        g_imguiSelectable("No saved .catstruct files!##saved_appearance_empty", false, 0, automaticSize);
        EndImGuiCombo();
        return 0;
    }

    changed = 0;
    fileCount = 0;

    do
    {
        if ((data.dwFileAttributes & FILE_ATTRIBUTE_DIRECTORY) != 0)
        {
            continue;
        }

        pathLength = snprintf(path, sizeof(path), "%s\\%s", directory, data.cFileName);

        if (pathLength <= 0 || (size_t)pathLength >= sizeof(path))
        {
            continue;
        }

        isActive = strcmp(g_activeAppearancePath, path) == 0;
        snprintf(fileLabel, sizeof(fileLabel), "%s%s##saved_appearance_file_%d", isActive ? "* " : "", data.cFileName, fileCount);

        if (g_imguiSelectable(fileLabel, isActive != 0, 0, fileNameSize))
        {
            if (LoadAppearanceFile(parts, defaultFrame, path))
            {
                changed = 1;
            }
        }

        g_imguiSameLine();
        AddHorizontalGap(DEBUG_HORIZONTAL_GAP);
        snprintf(deleteLabel, sizeof(deleteLabel), "DELETE##delete_saved_appearance_%d", fileCount);

        if (SelectableKeepPopupOpen(deleteLabel, false, deleteButtonSize))
        {
            DeleteAppearanceFile(path);
        }

        AddVerticalGap(DEBUG_FILE_ROW_VERTICAL_GAP);
        ++fileCount;
    } while (FindNextFileA(search, &data));

    FindClose(search);
    EndImGuiCombo();
    return changed;
}

int CopyAppearance(const uint8_t* parts)
{
    char text[APPEARANCE_TEXT_BUFFER_SIZE];
    int textLength;
    HANDLE memory;
    void* destination;
    void* ownerWindow;

    textLength = FormatAppearanceText(parts, text, sizeof(text));

    if (!textLength)
    {
        AddDebugMessage("Copy failed: Appearance text was too large!");
        return 0;
    }

    ownerWindow = GetActiveWindow();

    if (!OpenClipboard(ownerWindow))
    {
        AddDebugMessage("Copy failed: Clipboard is busy!");
        return 0;
    }

    if (!EmptyClipboard())
    {
        CloseClipboard();
        AddDebugMessage("Copy failed: Clipboard could not be cleared!");
        return 0;
    }

    memory = GlobalAlloc(GMEM_MOVEABLE, (size_t)textLength + 1U);
    destination = memory ? GlobalLock(memory) : NULL;

    if (!destination)
    {
        if (memory)
        {
            GlobalFree(memory);
        }

        CloseClipboard();
        AddDebugMessage("Copy failed: Clipboard memory unavailable!");
        return 0;
    }

    memcpy(destination, text, (size_t)textLength + 1U);
    GlobalUnlock(memory);

    if (!SetClipboardData(CF_TEXT, memory))
    {
        GlobalFree(memory);
        CloseClipboard();
        AddDebugMessage("Copy failed: Clipboard rejected the text!");
        return 0;
    }

    CloseClipboard();
    AddDebugMessage("Copied data to clipboard!");
    Log("Copied data to the clipboard!");
    return 1;
}

static int BuildScreenshotDirectory(char* directory, size_t directorySize)
{
    char modulePath[MAX_PATH];
    char* slash;
    int length;

    if (!directory || directorySize == 0 || !g_module || !GetModuleFileNameA(g_module, modulePath, MAX_PATH))
    {
        return 0;
    }

    slash = strrchr(modulePath, '\\');

    if (!slash)
    {
        return 0;
    }

    *slash = '\0';
    length = snprintf(directory, directorySize, "%s\\cat_images", modulePath);
    return length > 0 && (size_t)length < directorySize;
}

static int EnsureScreenshotDirectory(char* directory, size_t directorySize)
{
    DWORD error;

    if (!BuildScreenshotDirectory(directory, directorySize))
    {
        AddDebugMessage("Screenshot failed: Mod DLL directory was not found!");
        return 0;
    }

    if (CreateDirectoryA(directory, NULL))
    {
        return 1;
    }

    error = GetLastError();

    if (error == ERROR_ALREADY_EXISTS)
    {
        return 1;
    }

    AddDebugMessage("Screenshot failed: cat_images could not be created!");
    Log("Could not create screenshot directory %s (error %lu)!", directory, error);
    return 0;
}

static uint32_t UpdatePngCrc32(uint32_t crc, const uint8_t* data, size_t length)
{
    uint32_t value;
    int bit;

    while (length--)
    {
        crc ^= *data++;

        for (bit = 0; bit < 8; ++bit)
        {
            value = 0U - (crc & 1U);
            crc = (crc >> 1) ^ (0xEDB88320U & value);
        }
    }

    return crc;
}

static uint32_t PngAdler32(const uint8_t* data, size_t length)
{
    uint32_t first;
    uint32_t second;
    size_t block;

    first = 1U;
    second = 0U;

    while (length)
    {
        block = length > 5552U ? 5552U : length;
        length -= block;

        while (block--)
        {
            first += *data++;
            second += first;
        }

        first %= 65521U;
        second %= 65521U;
    }

    return (second << 16) | first;
}

static void StoreBigEndian32(uint8_t* output, uint32_t value)
{
    output[0] = (uint8_t)(value >> 24);
    output[1] = (uint8_t)(value >> 16);
    output[2] = (uint8_t)(value >> 8);
    output[3] = (uint8_t)value;
}

static int WriteFileBytes(HANDLE file, const void* data, size_t length)
{
    const uint8_t* cursor;
    DWORD block;
    DWORD written;

    cursor = (const uint8_t*)data;

    while (length)
    {
        block = length > 0x40000000U ? 0x40000000U : (DWORD)length;
        written = 0;

        if (!WriteFile(file, cursor, block, &written, NULL) || written != block)
        {
            return 0;
        }

        cursor += block;
        length -= block;
    }

    return 1;
}

static int WritePngChunk(HANDLE file, const char type[4], const uint8_t* data, size_t length)
{
    uint8_t lengthBytes[4];
    uint8_t crcBytes[4];
    uint32_t crc;

    if (length > 0xFFFFFFFFU)
    {
        return 0;
    }

    StoreBigEndian32(lengthBytes, (uint32_t)length);
    crc = UpdatePngCrc32(0xFFFFFFFFU, (const uint8_t*)type, 4);
    crc = UpdatePngCrc32(crc, data, length) ^ 0xFFFFFFFFU;
    StoreBigEndian32(crcBytes, crc);
    return WriteFileBytes(file, lengthBytes, sizeof(lengthBytes)) && WriteFileBytes(file, type, 4) && WriteFileBytes(file, data, length) && WriteFileBytes(file, crcBytes, sizeof(crcBytes));
}

static int WriteRgbaPng(const char* path, const uint8_t* pixels, int width, int height)
{
    static const uint8_t signature[8] = { 137U, 80U, 78U, 71U, 13U, 10U, 26U, 10U };
    static const uint8_t empty[1] = { 0U };
    uint8_t header[13];
    uint8_t* raw;
    uint8_t* compressed;
    uint8_t* output;
    const uint8_t* input;
    HANDLE file;
    size_t rowBytes;
    size_t rawSize;
    size_t blockCount;
    size_t compressedSize;
    size_t remaining;
    size_t blockSize;
    size_t row;
    uint32_t adler;
    uint16_t length16;
    int success;

    if (!path || !pixels || width <= 0 || height <= 0)
    {
        return 0;
    }

    rowBytes = (size_t)width * 4U;

    if (rowBytes / 4U != (size_t)width || (size_t)height > ((size_t)-1) / (rowBytes + 1U))
    {
        return 0;
    }

    rawSize = (rowBytes + 1U) * (size_t)height;
    blockCount = (rawSize + 65534U) / 65535U;

    if (blockCount > (((size_t)-1) - rawSize - 6U) / 5U)
    {
        return 0;
    }

    compressedSize = 2U + rawSize + blockCount * 5U + 4U;

    raw = (uint8_t*)malloc(rawSize);
    compressed = (uint8_t*)malloc(compressedSize);

    if (!raw || !compressed)
    {
        free(compressed);
        free(raw);
        return 0;
    }

    for (row = 0; row < (size_t)height; ++row)
    {
        raw[row * (rowBytes + 1U)] = 0U;
        memcpy(raw + row * (rowBytes + 1U) + 1U, pixels + row * rowBytes, rowBytes);
    }

    output = compressed;
    *output++ = 0x78U;
    *output++ = 0x01U;
    input = raw;
    remaining = rawSize;

    while (remaining)
    {
        blockSize = remaining > 65535U ? 65535U : remaining;
        *output++ = blockSize == remaining ? 1U : 0U;
        length16 = (uint16_t)blockSize;
        *output++ = (uint8_t)length16;
        *output++ = (uint8_t)(length16 >> 8);
        length16 = (uint16_t)~length16;
        *output++ = (uint8_t)length16;
        *output++ = (uint8_t)(length16 >> 8);
        memcpy(output, input, blockSize);
        output += blockSize;
        input += blockSize;
        remaining -= blockSize;
    }

    adler = PngAdler32(raw, rawSize);
    StoreBigEndian32(output, adler);
    output += 4;

    memset(header, 0, sizeof(header));
    StoreBigEndian32(header, (uint32_t)width);
    StoreBigEndian32(header + 4, (uint32_t)height);
    header[8] = 8U;
    header[9] = 6U;

    file = CreateFileA(path, GENERIC_WRITE, FILE_SHARE_READ, NULL, CREATE_ALWAYS, FILE_ATTRIBUTE_NORMAL, NULL);

    if (file == INVALID_HANDLE_VALUE)
    {
        free(compressed);
        free(raw);
        return 0;
    }

    success = WriteFileBytes(file, signature, sizeof(signature)) && WritePngChunk(file, "IHDR", header, sizeof(header)) && WritePngChunk(file, "IDAT", compressed, (size_t)(output - compressed)) && WritePngChunk(file, "IEND", empty, 0);
    CloseHandle(file);
    free(compressed);
    free(raw);

    if (!success)
    {
        DeleteFileA(path);
    }

    return success;
}

static int ReadScreenshotCurrentFrame(uint8_t** outPixels, int* outWidth, int* outHeight)
{
    GLboolean doubleBuffered;
    GLint viewport[4];
    GLint previousPackAlignment;
    GLint previousReadBuffer;
    GLenum captureBuffer;
    uint8_t* pixels;
    size_t pixelCount;
    int width;
    int height;

    if (!outPixels || !outWidth || !outHeight)
    {
        return 0;
    }

    *outPixels = NULL;
    *outWidth = 0;
    *outHeight = 0;

    glGetIntegerv(GL_VIEWPORT, viewport);

    /* 
    * Capture the whole framebuffer. CatAppearanceUI.b0 is authored in Flash
    * stage space, but the native CatVisual is transformed by the game renderer,
    * so its framebuffer X position can therefore land on either side of the screen...
    */
    width = viewport[2];
    height = viewport[3];

    if (width <= 0 || height <= 0 || width > SCREENSHOT_MAX_DIMENSION || height > SCREENSHOT_MAX_DIMENSION || width > 0x7FFFFFFF / height)
    {
        AddDebugMessage("Screenshot failed: Invalid OpenGL viewport!");
        return 0;
    }

    pixelCount = (size_t)width * (size_t)height;

    if (pixelCount > SCREENSHOT_MAX_PIXELS)
    {
        AddDebugMessage("Screenshot failed: Viewport is too large!");
        return 0;
    }

    pixels = (uint8_t*)malloc(pixelCount * 4U);

    if (!pixels)
    {
        AddDebugMessage("Screenshot failed: Not enough memory!");
        return 0;
    }

    /* This hook runs after the scene has rendered but before the window swap...
    * Read the current back buffer instead of GL_FRONT: Front-buffer contents
    * can lag indefinitely under flip-model presentation, caused the white
    * matte pass to keep seeing the preceding black frame on some systems I think...
    */
    doubleBuffered = GL_FALSE;
    glGetBooleanv(GL_DOUBLEBUFFER, &doubleBuffered);
    captureBuffer = doubleBuffered ? GL_BACK : GL_FRONT;

    glFinish();
    glGetIntegerv(GL_PACK_ALIGNMENT, &previousPackAlignment);
    glGetIntegerv(GL_READ_BUFFER, &previousReadBuffer);
    glReadBuffer(captureBuffer);
    glPixelStorei(GL_PACK_ALIGNMENT, 1);
    glReadPixels(viewport[0], viewport[1], width, height, GL_RGBA, GL_UNSIGNED_BYTE, pixels);
    glPixelStorei(GL_PACK_ALIGNMENT, previousPackAlignment);
    glReadBuffer((GLenum)previousReadBuffer);

    *outPixels = pixels;
    *outWidth = width;
    *outHeight = height;
    return 1;
}

static int ScreenshotMedian3(int first, int second, int third)
{
    if (first > second)
    {
        int temporary = first;
        first = second;
        second = temporary;
    }

    if (second > third)
    {
        int temporary = second;
        second = third;
        third = temporary;
    }

    if (first > second)
    {
        second = first;
    }

    return second;
}

static int ScreenshotFramesHaveDifferentMatte(const uint8_t* blackFrame, const uint8_t* whiteFrame, int width, int height)
{
    size_t changedPixels;
    size_t pixelCount;
    size_t requiredPixels;
    size_t index;
    const uint8_t* blackPixel;
    const uint8_t* whitePixel;
    int redDifference;
    int greenDifference;
    int blueDifference;
    int medianDifference;

    if (!blackFrame || !whiteFrame || width <= 0 || height <= 0)
    {
        return 0;
    }

    pixelCount = (size_t)width * (size_t)height;
    requiredPixels = pixelCount * SCREENSHOT_MINIMUM_MATTE_COVERAGE_PERCENT / 100U;

    if (requiredPixels < SCREENSHOT_MINIMUM_COMPONENT_PIXELS)
    {
        requiredPixels = SCREENSHOT_MINIMUM_COMPONENT_PIXELS;
    }

    changedPixels = 0;

    for (index = 0; index < pixelCount; ++index)
    {
        blackPixel = blackFrame + index * 4U;
        whitePixel = whiteFrame + index * 4U;
        redDifference = (int)whitePixel[0] - (int)blackPixel[0];
        greenDifference = (int)whitePixel[1] - (int)blackPixel[1];
        blueDifference = (int)whitePixel[2] - (int)blackPixel[2];
        medianDifference = ScreenshotMedian3(redDifference, greenDifference, blueDifference);

        if (medianDifference >= SCREENSHOT_MINIMUM_MATTE_DELTA)
        {
            ++changedPixels;

            if (changedPixels >= requiredPixels)
            {
                return 1;
            }
        }
    }

    return 0;
}

static int ScreenshotFrameDimensionsMatch(int width, int height)
{
    if (width == g_screenshotFrameWidth && height == g_screenshotFrameHeight)
    {
        return 1;
    }

    AddDebugMessage("Screenshot failed: The viewport changed during capture!");
    return 0;
}

static int ScreenshotRoundedDivide(int numerator, int denominator)
{
    if (denominator <= 0)
    {
        return 0;
    }

    if (numerator >= 0)
    {
        return (numerator + denominator / 2) / denominator;
    }

    return -((-numerator + denominator / 2) / denominator);
}

static uint8_t ReconstructIsolatedScreenshotAlpha(const uint8_t* visibleBlackPixel, const uint8_t* visibleWhitePixel, const uint8_t* backgroundBlackPixel, const uint8_t* backgroundWhitePixel)
{
    int channelAlpha[3];
    int validChannels;
    int backgroundRange;
    int visibleRange;
    int alpha;
    int channel;

    validChannels = 0;

    for (channel = 0; channel < 3; ++channel)
    {
        backgroundRange = (int)backgroundWhitePixel[channel] - (int)backgroundBlackPixel[channel];

        if (backgroundRange < SCREENSHOT_MINIMUM_TRANSMISSION_RANGE)
        {
            continue;
        }

        visibleRange = (int)visibleWhitePixel[channel] - (int)visibleBlackPixel[channel];

        if (visibleRange < 0)
        {
            visibleRange = 0;
        }

        if (visibleRange > backgroundRange)
        {
            visibleRange = backgroundRange;
        }

        alpha = 255 - (visibleRange * 255 + backgroundRange / 2) / backgroundRange;

        if (alpha < 0) alpha = 0;
        if (alpha > 255) alpha = 255;
        channelAlpha[validChannels++] = alpha;
    }

    if (validChannels == 0)
    {
        return 0U;
    }

    if (validChannels == 1)
    {
        return (uint8_t)channelAlpha[0];
    }

    if (validChannels == 2)
    {
        return (uint8_t)((channelAlpha[0] + channelAlpha[1] + 1) / 2);
    }

    return (uint8_t)ScreenshotMedian3(channelAlpha[0], channelAlpha[1], channelAlpha[2]);
}

static uint8_t ReconstructIsolatedScreenshotColorChannel(uint8_t visibleBlackValue, uint8_t visibleWhiteValue, uint8_t backgroundBlackValue, uint8_t backgroundWhiteValue, uint8_t alpha)
{
    int backgroundRange;
    int denominator;
    int blackEstimate;
    int whiteEstimate;
    int value;

    if (alpha == 0U)
    {
        return 0U;
    }

    backgroundRange = (int)backgroundWhiteValue - (int)backgroundBlackValue;

    if (backgroundRange < SCREENSHOT_MINIMUM_TRANSMISSION_RANGE)
    {
        return 0U;
    }

    denominator = backgroundRange * (int)alpha;
    blackEstimate = ScreenshotRoundedDivide(((int)visibleBlackValue - (int)backgroundBlackValue) * 65025, denominator);
    whiteEstimate = 255 + ScreenshotRoundedDivide(((int)visibleWhiteValue - (int)backgroundWhiteValue) * 65025, denominator);

    if (blackEstimate < 0) blackEstimate = 0;
    if (blackEstimate > 255) blackEstimate = 255;
    if (whiteEstimate < 0) whiteEstimate = 0;
    if (whiteEstimate > 255) whiteEstimate = 255;

    value = (blackEstimate + whiteEstimate + 1) / 2;
    return (uint8_t)value;
}

int CaptureScreenshotBlackPass(void)
{
    uint8_t* pixels;
    int width;
    int height;

    pixels = NULL;
    width = 0;
    height = 0;

    if (!ReadScreenshotCurrentFrame(&pixels, &width, &height))
    {
        return -1;
    }

    free(g_screenshotVisibleBlackFrame);
    g_screenshotVisibleBlackFrame = pixels;
    g_screenshotFrameWidth = width;
    g_screenshotFrameHeight = height;
    return 1;
}

int CaptureScreenshotWhitePass(void)
{
    uint8_t* pixels;
    int width;
    int height;

    if (!g_screenshotVisibleBlackFrame || g_screenshotFrameWidth <= 0 || g_screenshotFrameHeight <= 0)
    {
        AddDebugMessage("Screenshot failed: The visible black pass was not captured!");
        return -1;
    }

    pixels = NULL;
    width = 0;
    height = 0;

    if (!ReadScreenshotCurrentFrame(&pixels, &width, &height))
    {
        return -1;
    }

    if (!ScreenshotFrameDimensionsMatch(width, height))
    {
        free(pixels);
        return -1;
    }

    if (!ScreenshotFramesHaveDifferentMatte(g_screenshotVisibleBlackFrame, pixels, width, height))
    {
        free(pixels);
        return 0;
    }

    free(g_screenshotVisibleWhiteFrame);
    g_screenshotVisibleWhiteFrame = pixels;
    return 1;
}

int CaptureScreenshotBackgroundBlackPass(void)
{
    uint8_t* pixels;
    int width;
    int height;

    if (!g_screenshotVisibleBlackFrame || !g_screenshotVisibleWhiteFrame || g_screenshotFrameWidth <= 0 || g_screenshotFrameHeight <= 0)
    {
        AddDebugMessage("Screenshot failed: The visible render passes were not captured!");
        return -1;
    }

    pixels = NULL;
    width = 0;
    height = 0;

    if (!ReadScreenshotCurrentFrame(&pixels, &width, &height))
    {
        return -1;
    }

    if (!ScreenshotFrameDimensionsMatch(width, height))
    {
        free(pixels);
        return -1;
    }

    free(g_screenshotBackgroundBlackFrame);
    g_screenshotBackgroundBlackFrame = pixels;
    return 1;
}

int CaptureCatScreenshot(void)
{
    SYSTEMTIME now;
    uint8_t* backgroundWhiteFrame;
    uint8_t* alphaMask;
    uint8_t* output;
    const uint8_t* visibleBlackPixel;
    const uint8_t* visibleWhitePixel;
    const uint8_t* backgroundBlackPixel;
    const uint8_t* backgroundWhitePixel;
    uint8_t* outputPixel;
    char directory[MAX_PATH + 32];
    char outputPath[800];
    size_t pixelCount;
    size_t index;
    size_t sourceIndex;
    size_t outputIndex;
    int width;
    int height;
    int x;
    int y;
    int left;
    int bottom;
    int right;
    int top;
    int area;
    int outputWidth;
    int outputHeight;
    int outputX;
    int outputY;
    int sourceX;
    int sourceY;
    int success;
    uint8_t alpha;

    if (!g_screenshotVisibleBlackFrame || !g_screenshotVisibleWhiteFrame || !g_screenshotBackgroundBlackFrame || g_screenshotFrameWidth <= 0 || g_screenshotFrameHeight <= 0)
    {
        AddDebugMessage("Screenshot failed: The required isolation passes were not captured!");
        return -1;
    }

    backgroundWhiteFrame = NULL;
    width = 0;
    height = 0;

    if (!ReadScreenshotCurrentFrame(&backgroundWhiteFrame, &width, &height))
    {
        return -1;
    }

    if (!ScreenshotFrameDimensionsMatch(width, height))
    {
        free(backgroundWhiteFrame);
        return -1;
    }

    if (!ScreenshotFramesHaveDifferentMatte(g_screenshotBackgroundBlackFrame, backgroundWhiteFrame, width, height))
    {
        free(backgroundWhiteFrame);
        return 0;
    }

    if (!EnsureScreenshotDirectory(directory, sizeof(directory)))
    {
        free(backgroundWhiteFrame);
        return -1;
    }

    pixelCount = (size_t)width * (size_t)height;
    alphaMask = (uint8_t*)malloc(pixelCount);

    if (!alphaMask)
    {
        free(backgroundWhiteFrame);
        AddDebugMessage("Screenshot failed: Not enough memory for alpha reconstruction!");
        return -1;
    }

    for (y = 0; y < height; ++y)
    {
        for (x = 0; x < width; ++x)
        {
            index = (size_t)y * (size_t)width + (size_t)x;
            visibleBlackPixel = g_screenshotVisibleBlackFrame + index * 4U;
            visibleWhitePixel = g_screenshotVisibleWhiteFrame + index * 4U;
            backgroundBlackPixel = g_screenshotBackgroundBlackFrame + index * 4U;
            backgroundWhitePixel = backgroundWhiteFrame + index * 4U;
            alpha = ReconstructIsolatedScreenshotAlpha(visibleBlackPixel, visibleWhitePixel, backgroundBlackPixel, backgroundWhitePixel);

            if (alpha <= SCREENSHOT_ALPHA_THRESHOLD)
            {
                alpha = 0U;
            }

            alphaMask[index] = alpha;
        }
    }

    left = width;
    bottom = height;
    right = -1;
    top = -1;
    area = 0;

    for (y = 0; y < height; ++y)
    {
        for (x = 0; x < width; ++x)
        {
            index = (size_t)y * (size_t)width + (size_t)x;

            if (alphaMask[index] == 0U)
            {
                continue;
            }

            ++area;

            if (x < left) left = x;
            if (x > right) right = x;
            if (y < bottom) bottom = y;
            if (y > top) top = y;
        }
    }

    if (area < SCREENSHOT_MINIMUM_COMPONENT_PIXELS || right < left || top < bottom)
    {
        free(alphaMask);
        free(backgroundWhiteFrame);
        AddDebugMessage("Screenshot failed: Cat pixels were not found after background isolation!");
        return -1;
    }

    left -= SCREENSHOT_PADDING;
    bottom -= SCREENSHOT_PADDING;
    right += SCREENSHOT_PADDING;
    top += SCREENSHOT_PADDING;

    if (left < 0) { left = 0; }
    if (bottom < 0) { bottom = 0; }
    if (right >= width) { right = width - 1; }
    if (top >= height) { top = height - 1; }

    outputWidth = right - left + 1;
    outputHeight = top - bottom + 1;
    output = (uint8_t*)calloc((size_t)outputWidth * (size_t)outputHeight, 4U);

    if (!output)
    {
        free(alphaMask);
        free(backgroundWhiteFrame);
        AddDebugMessage("Screenshot failed: Not enough memory for PNG!");
        return -1;
    }

    for (outputY = 0; outputY < outputHeight; ++outputY)
    {
        sourceY = top - outputY;

        for (outputX = 0; outputX < outputWidth; ++outputX)
        {
            sourceX = left + outputX;
            sourceIndex = (size_t)sourceY * (size_t)width + (size_t)sourceX;
            alpha = alphaMask[sourceIndex];

            if (alpha == 0U)
            {
                continue;
            }

            visibleBlackPixel = g_screenshotVisibleBlackFrame + sourceIndex * 4U;
            visibleWhitePixel = g_screenshotVisibleWhiteFrame + sourceIndex * 4U;
            backgroundBlackPixel = g_screenshotBackgroundBlackFrame + sourceIndex * 4U;
            backgroundWhitePixel = backgroundWhiteFrame + sourceIndex * 4U;
            outputIndex = ((size_t)outputY * (size_t)outputWidth + (size_t)outputX) * 4U;
            outputPixel = output + outputIndex;
            outputPixel[0] = ReconstructIsolatedScreenshotColorChannel(visibleBlackPixel[0], visibleWhitePixel[0], backgroundBlackPixel[0], backgroundWhitePixel[0], alpha);
            outputPixel[1] = ReconstructIsolatedScreenshotColorChannel(visibleBlackPixel[1], visibleWhitePixel[1], backgroundBlackPixel[1], backgroundWhitePixel[1], alpha);
            outputPixel[2] = ReconstructIsolatedScreenshotColorChannel(visibleBlackPixel[2], visibleWhitePixel[2], backgroundBlackPixel[2], backgroundWhitePixel[2], alpha);
            outputPixel[3] = alpha;
        }
    }

    GetLocalTime(&now);
    snprintf(outputPath, sizeof(outputPath), "%s\\cat_%04u%02u%02u-%02u%02u%02u-%03u.png", directory, (unsigned int)now.wYear, (unsigned int)now.wMonth, (unsigned int)now.wDay, (unsigned int)now.wHour, (unsigned int)now.wMinute, (unsigned int)now.wSecond, (unsigned int)now.wMilliseconds);
    success = WriteRgbaPng(outputPath, output, outputWidth, outputHeight);
    free(output);
    free(alphaMask);
    free(backgroundWhiteFrame);

    if (!success)
    {
        AddDebugMessage("Screenshot failed while writing the PNG file!");
        return -1;
    }

    AddDebugMessage("Saved cat .png: %s", AppearanceFileName(outputPath));
    Log("Captured four-pass isolated cat PNG to %s (%dx%d); scene vignette, UI, and cursor were excluded!", outputPath, outputWidth, outputHeight);
    return 1;
}

int ExportAppearance(const uint8_t* parts)
{
    SYSTEMTIME now;
    char directory[MAX_PATH + 32];
    char outputPath[800];
    char text[APPEARANCE_TEXT_BUFFER_SIZE];
    DWORD written;
    HANDLE file;
    int textLength;
    int overwriting;

    if (!EnsureAppearanceDirectory(directory, sizeof(directory)))
    {
        return 0;
    }

    overwriting = g_activeAppearancePath[0] != '\0';

    if (overwriting)
    {
        snprintf(outputPath, sizeof(outputPath), "%s", g_activeAppearancePath);
    }
    else
    {
        GetLocalTime(&now);
        snprintf(outputPath, sizeof(outputPath), "%s\\cat_%04u%02u%02u-%02u%02u%02u.catstruct", directory, (unsigned int)now.wYear, (unsigned int)now.wMonth, (unsigned int)now.wDay, (unsigned int)now.wHour, (unsigned int)now.wMinute, (unsigned int)now.wSecond);
    }

    textLength = FormatAppearanceText(parts, text, sizeof(text));

    if (!textLength)
    {
        AddDebugMessage("Save failed: Text was too large!");
        return 0;
    }

    file = CreateFileA(outputPath, GENERIC_WRITE, FILE_SHARE_READ, NULL, CREATE_ALWAYS, FILE_ATTRIBUTE_NORMAL, NULL);

    if (file == INVALID_HANDLE_VALUE)
    {
        AddDebugMessage("Save failed: Could not create the .catstruct file!");
        Log("Export failed for %s (error %lu)", outputPath, GetLastError());
        return 0;
    }

    written = 0;

    if (!WriteFile(file, text, (DWORD)textLength, &written, NULL) || written != (DWORD)textLength)
    {
        CloseHandle(file);
        AddDebugMessage("Save failed while writing the .catstruct file!");
        return 0;
    }

    CloseHandle(file);
    snprintf(g_activeAppearancePath, sizeof(g_activeAppearancePath), "%s", outputPath);
    AddDebugMessage(overwriting ? "Updated: %s" : "Saved: %s", AppearanceFileName(outputPath));
    Log("Exported cat to %s", outputPath);
    return 1;
}